# $Id: $

PREFIX		?= ../_build/install

all::
install::
	@mkdir -p $(PREFIX)/bin
	cp -f ldlsat.sh $(PREFIX)/bin/ldlsat
	cp -f ldlmc.sh $(PREFIX)/bin/ldlmc

clean::;	find . -name '*~' | xargs rm -f
veryclean::
